---
title: "A rough guide to cold brew"
description: |
  While to the common librarian Cory Doctorow is merely known as champion for Open Access, the Creative Commons, the EFF etc., he is also a hell of a barrista, introducing many a young scholar - the author included - to the carnality of cold brew.  
  So, here is the rough guide for future reference. 
preview: cold_brew_cats.jpg
author:
- first_name: "Olaf"
  last_name: "Schmalfuß"
  orcid_id: 0000-0002-1919-3848
  url: https://www.datamercs.net
date: 2013-07-21
output:
  distill::distill_article:
    self_contained: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### // essential reading

[HOWTO attain radical hotel-room coffee independence](https://boingboing.net/2011/11/14/howto-attain-radical-hotel-roo.html)

easier  

[Cheap, easy, no-mess cold-brew coffee](https://boingboing.net/2013/07/20/cheap-easy-no-mess-cold-brew.html)  

but frankly: simply use your French Press and let the coarse ground coffee brew over night in your fridge...  
Enjoy!  

### // A prosaic how-to, or love letter

as given [here](https://craphound.com/homeland/Cory_Doctorow_-_Homeland.html) to its best by *Cory Doctorow*, in

> **Homeland**  

> You've had hot coffee before, and in the hands of a skilled maker, coffee can be amazing. But the fact is that coffee is one of the hardest things to get right in the world. Even with great beans and a great roast and great equipment, a little too much heat, the wrong grind, or letting things go on too long will produce a cup of bitterness. Coffee's full of different acids, and depending on the grind, temperature, roast, and method, you can "overextract" the acids from the beans, or overheat them and oxidize them, producing that awful taste you get at donut shops and Starbucks.  
> But there is Another Way. If you make coffee in cold water, you only extract the sweetest acids, the highly volatile flavors that hint at chocolate and caramel, the ones that boil away or turn to sourness under imperfect circumstances. Brewing coffee in cold water sounds weird, but in fact, it's just about the easiest way to make a cup (or a jar) of coffee.  
> Just grind coffee -- keep it coarse, with grains about the size of sea salt -- and combine it with twice as much water in an airtight jar. Give it a hard shake and stick it somewhere cool overnight (I used a cooler bag loaded with ice from ice camp and wrapped the whole thing in bubble wrap for insulation). In the morning, strain it through a colander and a paper coffee filter. What you've got now is coffee concentrate, which you can dilute with cold water to taste -- I go about half and half. If you're feeling fancy, serve it over ice.  
> Here's the thing: cold-brew coffee tastes amazing, and it's practically impossible to screw it up. Unlike espresso, where all the grounds have to be about the same size so that the high pressure water doesn't cause fracture lines in the "puck" of coffee that leave some of the coffee unextracted and the rest overextracted, cold-brew grounds can be just about any size. Seriously, you could grind it with a stone axe. Unlike drip coffee, which goes sour and bitter if you leave the grounds in contact with the water for too long, cold-brew just gets yummier and yummier (and more and more caffeinated!) the longer the grounds sit in the water. Cold-brewing in a jar is pretty much the easiest way to make coffee in the known universe -- if you don't mind waiting overnight for the brew -- and it produces the best-tasting, most potent coffee you've ever drunk. The only downside is that it's kind of a pain in the ass to clean up, but if you want to spend some more money, you can invest in various gadgets to make it easier to filter the grounds, from cheap little Toddy machines all the way up to hand-blown glass "Kyoto drippers" that look like something from a mad scientist's lab. But all you need to make a perfectly astounding cup of cold-brewed jet fuel is a mason jar, coffee, water, and something to strain it through. They've been making iced coffee this way in New Orleans for centuries, but for some unknown reason, it never seems to have caught on big-time.  
> [...]  
> It's funny watching someone take a sip of cold-brew for the first time, because it looks and smells strong, and it is, and coffee drinkers have been trained to think that "strong" equals "bitter." The first mouthful washes over your tongue and the coffee flavor wafts up the back of your throat and fills up your sinus cavity and your nose is all, "THIS IS INCREDIBLY STRONG!" And the flavor is strong, but there isn't a hint of bitterness. It's like someone took a cup of coffee and subtracted everything that wasn't totally delicious, and what's left behind is a pure, powerful coffee liquor made up of all these subtle flavors: citrus and cocoa and a bit of maple syrup, all overlaid on the basic and powerful coffee taste you know and love.  

(CC BY-NC-ND 3.0)


