---
title: "MarcEdit on the command line"
description: |
  A short description of the post.
author:
  - name: Olaf Schmalfuß
    url: https://www.datamercs.net
date: 2022-09-01
output:
  distill::distill_article:
    self_contained: true
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

That was the topic discussed recently by OCLC Research Library Partners metadata managers, initiated by Jennifer Baxmeyer of Princeton University and Sharon Farnel of the University of Alberta.  Many OCLC Research Library Partners use MarcEdit and/or other tools such as OpenRefine, scripts (e.g., Python, Ruby or Perl), and macros for metadata reconciliation and batch-processing

The command line tool is probably one of those under-used and unknown parts of MarcEdit.  The tool is a shim over the code libraries – exposing functionality from the command line, and making it easy to integrate with scripts written for automation purposes. 

MarcEdit includes a separate command-line tool that encapsulates a wide range of functionality.  The tool provides a GUIless interface that can be used within shell scripts or other automation tools. The command-line tool is available in all versions of MarcEdit.  On windows and Linux, the terminal version is run through a separate program: cmarcedit.exe. 
https://marcedit.reeset.net/cmarcedit-exe-using-the-command-line

https://marcedit.reeset.net/learning_marcedit/book-v-features-for-developers/chapter-4-working-with-marcedits-command-line-tools/

https://blog.reeset.net/archives/1078

he program current provides the following options (these options can be found by entering:

```
cmarcedit.exe -help
```






```
   MARC8 and UTF8
       The current Catmandu MARC tools are targetted for processing UTF8 encoded files.  When you
       have MARC8 encoded data tools like MarcEdit <https://marcedit.reeset.net/> or
       "yaz-marcdump" <https://software.indexdata.com/yaz/doc/yaz-marcdump.html> can be used to
       create a UTF8 encoded file:

          $ yaz-marcdump -f MARC-8 -t UTF-8 -o marc -l 9=97 marc21.raw > marc21.utf8.raw

   Convert a decomposed UTF8 file to a combined UTF8 file and vice versa
       For example, the character ae can be represented as

       "ae", that is the codepoint U+00E4 (two bytes c3 a4 in UTF-8 encoding), or as "aX", that
       is the two codepoints U+0061 U+0308 (three bytes 61 cc 88 in UTF-8).

       The uconf (libicu-dev Linux package) tool can be used to convert these types of files:

           $ uconv -x any-nfc < decomposed.txt > combined.txt
           $ uconv -x any-nfd < combined.txt > decomposed.txt
           
```





